import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main.jsx";
import About from "../components/About.jsx";
import Skills from "../components/Skills.jsx";
import Projects from "../components/Projects.jsx";
import Contact from "../components/Contact.jsx";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ranggo Pato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />

      <Projects />
      <Contact />
    </div>
  );
}
